### ISSUE TITLE
Implement server calls

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#10]
### Overview

Implement all Server calls in Rust based in the generated gRPC client. This includes all methods for the following CRUD operations, it is tightly connected to all operations on the database side tracked in #7

### Tasks

- [x] CREATE project
- [x] GET project
- [x] UPDATE project
- [x] DELETE project
- [x] CREATE collection
- [x] GET collection
- [x] UPDATE collection
- [x] DELETE collection
- [x] CREATE object
- [x] GET object
- [x] UPDATE object
- [x] DELETE object
- [x] CREATE object_group
- [x] GET object_group
- [x] UPDATE object_group
- [x] DELETE object_group
- [x] GET object via label
- [x] GET object_group via label
- [x] GET collection via label

### Discussions

**Comment by St4NNi** [comment]
Fixed in #34
