### ISSUE TITLE
Implement config handling

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#12]
### Overview

Implement a way to handle the server configuration using TOML config files.

### Tasks

- [x] TOML handling
- [ ] Documentation for TOML in README.md related to  #15
- [x] Environment variable option
- [ ] Doc for env-vars in README.md related to  #15

### Discussions

- What should be the default configuration method, TOML vs. env vars ?

**Comment by das-Abroxas** [comment]
Changed YAML to TOML since TOML is the default in Rust. Makes more sense in my opinion. 

For simplicity, in the first implementation there will be the possibility to write non-critical configuration parameters to a configuration file and security relevant parameters to environment variables.
