### ISSUE TITLE
Implement notification system

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#13]
### Overview

Implement the the necessary components to use NATS.io as notification service and allow authenticated access to it.

### Tasks

- [x] grpc API integration
- [x] CRUD resource notification handler
- [x] nats.io integration
- [x] nats.io integration tests

### Discussions
