### ISSUE TITLE
Add test infrastructure

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#14]
### Overview

Add the required test infrastructure for e2e, API and database tests, since all components are rather dependent on external access.

### Tasks

- [x] Unit tests for functions
- [x] Add codecov report to README.md
- [x] Integration tests for grpc API
- [x] Integration tests for database
- [x] CI/CD pipeline for automated e2e tests

### Discussions

- Should everything be unit-tested or are some functions only practical testable via integration tests ?

**Comment by St4NNi** [comment]
Fixed in #34
