### ISSUE TITLE
Add proper documentation

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/ArunaServer#15]
### Overview

Multiple layers of documentation are needed, developer documentation for contributors, usage documentation for setting up all components and databases, usage documentation for interaction with the API (may contain references to another repo e.g. ArunaAPI)

### Tasks

- [ ] Broad overview in README.md
- [ ] Readthedocs / github pages
- [ ] Broad descriptions in Readthedocs that describe the overall concepts / resources and their relations
- [ ] Developer documentation via. cargo docs / inline markdown
- [ ] Deployment documentation for users including database and setup requirements
- [ ] API documentation via. OpenAPI -> ArunaAPI
- [ ] User documentation for gRPC stubs

### Discussions

- How should these docs be organized structured ?
- Readthedocs Markdown vs. Mkdocs ?

**Comment by St4NNi** [comment]
I think we should use markdown, because rustdocs automatically support markdown formats.
