### ISSUE TITLE
Setup CI pipeline with Github actions

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#3]
### Overview

Setup a CI pipeline to test, validate and deploy the server.

### Tasks

- [x] Unit test application (cargo test)
- [x] Build `--release` full application (cargo build)
- [x] Integration test application (with test_db setup)
- [x] Build docker container and create DOCKERFILE
- [x] Push docker container to registry
- [x] Deploy and test container
- [x] Pipeline for dev branch and main branch 

### Discussions

- When should each step be tested ? On every commit / pr etc. ?
