### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/ArunaServer#31]
### Overview

This is an umbrella issue that should contain small (non-critical) issues and improvements that came up during testing. For major bugs pls open a dedicated issue.

### Tasks

- [x] S3 enforces a minimal multipart-size of 5Mib. API should throw an error if content-len is smaller than 5 MiB and `multipart == true`.
- [x] LabelOntology: enforce ontology on object creation / finish
- [x] Updates should be only exclusive for the latest object 
- [x] Update Object should create an ApiHash on every update! (GetObjects is already fixed)

### Discussions

- None
