### ISSUE TITLE
[Feature] Bundled downloads

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/ArunaServer#35]
### Overview

Bundled downloads would be a good idea. This could work via the following logic:

### Tasks

- [x] Request to create a bundle
- [x] Add bundle-id as hook / label
- [x] Enable dataproxy to download by bundle id
- [x] Bundle data in one archive (tgz, gzip) 

### Discussions

- Can we enable this to support shared downloads ?

**Comment by St4NNi** [comment]
Can collections be bundled together with objects. e.g. 2 Collection + X Objects from other collections ?

**Comment by St4NNi** [comment]
In a first iteration this should only include a list of object_ids.
