### ISSUE TITLE
[Feature] Service accounts tokens

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/ArunaServer#38]
### Overview

It should be possible to bind tokens to a specific project for service accounts. All admins from a specific project should be possible to edit and manage these tokens.

### Draft (revised)

An updated Draft / concept for a non breaking update to service accounts after 1.0.0. -> target release in 1.1.0.
To properly support service accounts we could re-use the existing authorization structures by expanding the internal 
database `user` to also include service accounts. This could be accomplished by a boolean flag `is_service_account`.

The regular `user service` and all user-related project methods like `AddUserToProject` etc. should be disabled for users with `is_service_account` set to true, instead a separate service_account service should be provided. In this, project admins can handle and manage service accounts for a specific project -> service accounts should be bound to a project.  By disabling the regular calls for service_accounts we can re-use the existing user / token logic while also enforcing only one project specific permission for a service account. 

#### Tasks
- [x] Disable methods for service accounts (All of `user`, all `user` related in Project`)
- [x] Implement service_account_service (already drafted in API)
- [x] Add a is_service_account flag to user (default FALSE)
- [x] Only project and global admins can manage service accounts

**Comment by St4NNi** [comment]
Updated the proposal with more information!
