### ISSUE TITLE
Create database migrations in Diesel for MVP

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#4]
### Overview

Create a migrations for each resource (project, collection, object, object_group) and each table. This is related to #6 and #7.

### Tasks

- [x] users
- [x] projects
- [x] endpoints
- [x] sources
- [x] objects
- [x] hash_type
- [x] object_locations
- [x] hashes
- [x] object_key_value
- [x] collection_version
- [x] collections
- [x] collection_key_value
- [x] required_labels(collection)
- [x] collection_objects
- [x] object_groups
- [x] collection_object_groups
- [x] object_group_key_value
- [x] object_group_objects
- [x] idps
- [x] external_user_ids
- [x] user_permissions
- [x] api_tokens
- [x] notification_stream_groups 

### Discussions
