### ISSUE TITLE
Implement database CRUD operations for resources

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#7]
### Overview

Implement the required database CRUD operations for tables. These should be the "raw" table crud operations, but they can link multiple actions together e.g. creating an `object` should also create all references and entries for `object_locations`, `object_key_value`, `collection_objects` etc. This is related to the issue #6

### Tasks

- [x] users
- [x] projects
- [x] endpoints
- [x] sources
- [x] objects
- [x] hash_type
- [x] object_locations
- [x] hashes
- [x] object_key_value
- [x] collection_version
- [x] collections
- [x] collection_key_value
- [x] required_labels(collection)
- [x] collection_objects
- [x] object_groups
- [x] collection_object_groups
- [x] object_group_key_value
- [x] object_group_objects
- [x] idps
- [x] external_user_ids
- [x] user_permissions
- [x] api_tokens
- [ ] notification_stream_groups

### Discussions

- Which of these tables should be handled in combined operations ?

**Comment by St4NNi** [comment]
All MVP targets are implemented, a long time ago (besides notifications -> this will be tracked in a separate issue). Close for now, fixed in #34
